# Generated by Django 5.2 on 2025-05-08 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_app', '0003_emploisdutemps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='archives/')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='iscae_app.matiere')),
            ],
        ),
    ]
